import type { Metadata } from "next";
import { Archivo, Besley,Homemade_Apple } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["100" , "200" , "300" , "400" , "500" , "600" , "700" , "800" , "900"],
})

const besley = Besley({
  variable: "--font-besley",
  style:["normal","italic"],
  subsets: ["latin"],
  weight: ["400" , "500" , "600" , "700" , "800" , "900"],
})

const homemade_apple = Homemade_Apple({
  variable: "--font-apple",
  style:["normal"],
  subsets: ["latin"],
  weight: ["400"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavBar/>
      <body
        className={`${archivo.variable} ${besley.variable} ${homemade_apple.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
